# Generated by Django 5.1.4 on 2025-09-30 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriconnectbackendapp', '0003_user_gender_user_title_farm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='farm',
            table='Farm',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
