# Generated by Django 5.1.4 on 2025-10-20 18:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriconnectbackendapp', '0005_crop_notification_userfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='code',
            field=models.IntegerField( default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crop',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='farm',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
