# Generated by Django 5.1.4 on 2025-10-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriconnectbackendapp', '0006_farm_code_alter_crop_id_alter_farm_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='code',
            field=models.IntegerField(),
        ),
    ]
