# Generated by Django 5.1.4 on 2025-10-20 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriconnectbackendapp', '0007_alter_farm_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='code',
        ),
    ]
