# Generated by Django 5.1.4 on 2025-10-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriconnectbackendapp', '0008_remove_farm_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='code',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
