# Generated by Django 5.1.4 on 2025-10-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriconnectbackendapp', '0009_farm_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
