# Generated by Django 5.1.4 on 2025-10-28 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriconnectbackendapp', '0010_alter_farm_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='photoperiod',
            field=models.CharField(default='Short Day Period', max_length=255),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('random_seed', models.IntegerField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='agriconnectbackendapp.crop')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='agriconnectbackendapp.farm')),
            ],
            options={
                'db_table': 'sensor',
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('ph', models.FloatField()),
                ('light_hours', models.FloatField()),
                ('light_intensity', models.FloatField()),
                ('rh', models.FloatField()),
                ('nitrogen', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('potassium', models.FloatField()),
                ('yield_value', models.FloatField()),
                ('category_ph', models.CharField(max_length=50)),
                ('soil_type', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=50)),
                ('n_ratio', models.FloatField()),
                ('p_ratio', models.FloatField()),
                ('k_ratio', models.FloatField()),
                ('plant_name', models.CharField(max_length=100)),
                ('photoperiod', models.CharField(max_length=100)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='agriconnectbackendapp.sensor')),
            ],
            options={
                'db_table': 'sensordata',
            },
        ),
    ]
