# Generated by Django 5.1.4 on 2025-11-07 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriconnectbackendapp', '0011_crop_photoperiod_sensor_sensordata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertility_level', models.CharField(max_length=50)),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertility_records', to='agriconnectbackendapp.sensor')),
                ('sensor_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fertility_record', to='agriconnectbackendapp.sensordata')),
            ],
            options={
                'db_table': 'fertilityrecord',
            },
        ),
    ]
