# Generated by Django 5.1.4 on 2025-11-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriconnectbackendapp', '0013_userdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='fcm_token',
            field=models.CharField(max_length=512),
        ),
    ]
