# Generated by Django 5.1.4 on 2025-11-15 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriconnectbackendapp', '0014_alter_userdevice_fcm_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('HIGH', 'High'), ('EXTREME', 'Extreme')], max_length=10)),
                ('weather_code', models.IntegerField()),
                ('alert_title', models.CharField(max_length=100)),
                ('recommendation', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agriconnectbackendapp.farm')),
            ],
        ),
    ]
