# Generated by Django 5.1.4 on 2025-11-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriconnectbackendapp', '0015_weatheralert'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='crop',
            table='crops',
        ),
        migrations.AlterModelTable(
            name='farm',
            table='farm',
        ),
        migrations.AlterModelTable(
            name='fertilityrecord',
            table='fertility_record',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notification',
        ),
        migrations.AlterModelTable(
            name='sensordata',
            table='sensor_data',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='userdevice',
            table='user_device',
        ),
        migrations.AlterModelTable(
            name='weatheralert',
            table='weather_alert',
        ),
    ]
