# Generated by Django 5.1.4 on 2025-11-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriconnectbackendapp', '0016_alter_crop_table_alter_farm_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilityrecord',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='recorded_at',
            field=models.DateTimeField(),
        ),
    ]
