# Generated by Django 5.1.4 on 2025-11-19 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriconnectbackendapp', '0017_alter_fertilityrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='recorded_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
